# workflow for repo 2
name: Repo 2 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    extends:
      - .github/workflows/build.yml
