# repo2-workflow.yml

name: Repo 2 Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-common-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Common Workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.repos.createDispatchEvent({
              owner: 'gulshkr',
              repo: 'common-workflow',
              event_type: 'trigger-common-workflow',
            });
            console.log(response.data);
